<div class="page-header">
    <div class="page-content-area">
        <div class="page-header">
            <h1>
                <?php echo $this->translate('Modifier List'); ?> 

            </h1>
        </div><!-- /.page-header -->

<?php 
/*echo "<pre>";
print_r($liste);
exit;*/

?> 
        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('lists', array('action' => 'editcord', 'id' => $id)));
        $form->prepare();

        echo $this->form()->openTag($form) . PHP_EOL;
        ?>
        <?php echo $this->formInput($form->get('list_id')); ?>
        <div class=" col-xs-12 col-lg-12">

            <?php if ($this->messageErreur == "true") {
                ?>
                <div class="alert alert-block alert-danger">
                    <p style="color: red;font-weight: bold;">
                        <?php echo $this->translate($this->message) ?>
                    </p>
                </div>
            <?php } ?>



            <?php if ($this->success == "true") {
                ?>

                <div class="alert alert-block alert-success">
                    <p style="font-weight: bold;">
                        <?php echo $this->translate($this->messageSuccess) ?>
                    </p>
                </div>
            <?php } ?>

        </div>
       <div class=" col-xs-12 col-lg-6">
            <div class="profile-user-info profile-user-info-striped">
                
                
                <div class="profile-info-row">
                    <div class="profile-info-name">Logo </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="about">
                           <img id="carte" class="editable img-responsive editable-click editable-empty" alt="<?php echo $this->escapeHtml($liste->list_nom); ?>" 
                                     src="/assets/logo/<?php echo $this->escapeHtml($liste->list_logo); ?>" style="width: 70px;">
                        </span>
                    </div>
                </div>
                
                <div class="profile-info-row">
                    <div class="profile-info-name"> Image   </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="about">
                            
                            <?php if($liste->list_image){ ?>
                                <a href="/assets/imageList/<?php echo $this->escapeHtml($liste->list_image); ?>" target="_blank">
                                <img id="carte" class="editable img-responsive editable-click editable-empty" alt="<?php echo $this->escapeHtml($liste->list_nom); ?>" 
                                     src="/assets/imageList/<?php echo $this->escapeHtml($liste->list_image); ?>" style="width: 70px;">
                                </a>
                                  <?php }else{ echo $this->escapeHtml($liste->list_nom); } ?>
                            
                        </span>
                    </div>
                </div>
                
                <div class="profile-info-row">
                    <div class="profile-info-name">
                      Image Programme 
                    </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="username">
                           <?php if($liste->list_imageGroup){ ?>
                                  <a href="/assets/imageListGroup/<?php echo $this->escapeHtml($liste->list_imageGroup); ?>" target="_blank">
                                <img id="carte" class="editable img-responsive editable-click editable-empty" alt="<?php echo $this->escapeHtml($liste->list_nom); ?>" 
                                     src="/assets/imageListGroup/<?php echo $this->escapeHtml($liste->list_imageGroup); ?>" style="width: 70px;">
                                 </a>
                                <?php }else{ echo $this->escapeHtml($liste->list_nom); } ?>
                        </span>
                    </div>
                </div>
               
                
               
              

              
            </div>

        </div>

        <div class=" col-xs-12 col-lg-6">
            <div class="profile-user-info profile-user-info-striped">
                
                    <div class="profile-info-row">
                    <div class="profile-info-name"> Type List  </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="country">
                            
                             <?php
                               // echo $this->escapeHtml($list->list_type);
                                switch ($liste->list_type) {
                                    case 1:
                                        echo "حزب";
                                        break;
                                    case 2:
                                        echo "الائتلاف";
                                        break;
                                    case 3:
                                        echo "مستقل";
                                        break;
                                }
                                ?>
                        </span>
                    </div>
                </div>
                 
                <div class="profile-info-row">
                    <div class="profile-info-name"> Nom  </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="country">
                         <?php echo $this->escapeHtml($liste->list_nom); ?>
                        </span>
                    </div>
                </div>

                <div class="profile-info-row">
                    <div class="profile-info-name"> list tete </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="country">
                        <?php echo $this->escapeHtml($liste->list_tete); ?>
                        </span>
                    </div>
                </div>
                
                
                <div class="profile-info-row">
                    <div class="profile-info-name"> Numero </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="country">
                        <?php echo $this->escapeHtml($liste->list_num); ?>
                        </span>
                    </div>
                </div>

                  
                
                <div class="profile-info-row">
                    <div class="profile-info-name"> <?php echo $this->formLabel($form->get('list_valide')); ?> </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="country"><?php
                            echo $this->formElement($form->get('list_valide'));
                            echo $this->formElementErrors($form->get('list_valide'));
                            ?></span>
                    </div>
                </div>

               
               

            </div>

        </div>
        <div class="space-20"></div>
        <div style="text-align: right;">
            <button class="btn btn-primary" style="  margin-right: 5px;">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                <a style="  color: white;"  href="/lists"  >
                    <?php echo $this->translate('Retour'); ?>
                </a>   
            </button>
            <?php
            echo $this->formInput($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?>


        </div>
    </div>
</div>