<div class="page-header">
    <div class="page-content-area">
        <div class="page-header">
            <h1>
                <?php echo $this->translate('Modifier List'); ?> 

            </h1>
        </div><!-- /.page-header -->


        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('lists', array('action' => 'edit', 'id' => $id)));
        $form->prepare();

        echo $this->form()->openTag($form) . PHP_EOL;
        ?>
        <?php echo $this->formInput($form->get('list_id')); ?>
        <div class=" col-xs-12 col-lg-12">

            <?php if ($this->messageErreur == "true") {
                ?>
                <div class="alert alert-block alert-danger">
                    <p style="color: red;font-weight: bold;">
                        <?php echo $this->translate($this->message) ?>
                    </p>
                </div>
            <?php } ?>



            <?php if ($this->success == "true") {
                ?>

                <div class="alert alert-block alert-success">
                    <p style="font-weight: bold;">
                        <?php echo $this->translate($this->messageSuccess) ?>
                    </p>
                </div>
            <?php } ?>

        </div>
       <div class=" col-xs-12 col-lg-6">
            <div class="profile-user-info profile-user-info-striped">
                
                
                <div class="profile-info-row">
                    <div class="profile-info-name"> <?php echo $this->formLabel($form->get('list_idDelegation')); ?>  </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="about"> <?php
                            echo $this->formElement($form->get('list_idDelegation'));
                            echo $this->formElementErrors($form->get('list_idDelegation'));
                            ?></span>
                    </div>
                </div>
                
                <div class="profile-info-row">
                    <div class="profile-info-name"> <?php echo $this->formLabel($form->get('list_type')); ?>  </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="about"> <?php
                            echo $this->formElement($form->get('list_type'));
                            echo $this->formElementErrors($form->get('list_type'));
                            ?></span>
                    </div>
                </div>
                
                <div class="profile-info-row">
                    <div class="profile-info-name">
                        <?php echo $this->formLabel($form->get('list_nom')); ?> 
                    </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="username">
                            <?php
                            echo $this->formInput($form->get('list_nom'));
                            echo $this->formElementErrors($form->get('list_nom'));
                            ?>
                        </span>
                    </div>
                </div>
                
                 <div class="profile-info-row">
                    <div class="profile-info-name">
                        <?php echo $this->formLabel($form->get('list_num')); ?> 
                    </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="username">
                            <?php
                            echo $this->formInput($form->get('list_num'));
                            echo $this->formElementErrors($form->get('list_num'));
                            ?>
                        </span>
                    </div>
                </div>
                
                <div class="profile-info-row">
                    <div class="profile-info-name"> 
                        <?php echo $this->formLabel($form->get('list_tete')); ?> 
                    </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="username">
                            <?php
                            echo $this->formInput($form->get('list_tete'));
                            echo $this->formElementErrors($form->get('list_tete'));
                            ?>
                        </span>
                    </div>
                </div>
                
               
              

              
            </div>

        </div>

        <div class=" col-xs-12 col-lg-6">
            <div class="profile-user-info profile-user-info-striped">
                
                    <div class="profile-info-row">
                    <div class="profile-info-name"> <?php echo $this->formLabel($form->get('list_logo')); ?> </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="country"><?php
                            echo $this->formElement($form->get('list_logo'));
                            echo $this->formElementErrors($form->get('list_logo'));
                            ?></span>
                    </div>
                </div>
                 
                <div class="profile-info-row">
                    <div class="profile-info-name"> <?php echo $this->formLabel($form->get('list_image')); ?> </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="country"><?php
                            echo $this->formElement($form->get('list_image'));
                            echo $this->formElementErrors($form->get('list_image'));
                            ?></span>
                    </div>
                </div>

                <div class="profile-info-row">
                    <div class="profile-info-name"> <?php echo $this->formLabel($form->get('list_imageGroup')); ?> </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="country"><?php
                            echo $this->formElement($form->get('list_imageGroup'));
                            echo $this->formElementErrors($form->get('list_imageGroup'));
                            ?></span>
                    </div>
                </div>

                  
                
                <div class="profile-info-row">
                    <div class="profile-info-name"> <?php echo $this->formLabel($form->get('list_valide')); ?> </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="country"><?php
                            echo $this->formElement($form->get('list_valide'));
                            echo $this->formElementErrors($form->get('list_valide'));
                            ?></span>
                    </div>
                </div>

                <div class="profile-info-row">
                    <div class="profile-info-name"> <?php echo $this->formLabel($form->get('list_publie')); ?> </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="country"><?php
                            echo $this->formElement($form->get('list_publie'));
                            echo $this->formElementErrors($form->get('list_publie'));
                            ?></span>
                    </div>
                </div>

               

            </div>

        </div>
        <div class="space-20"></div>
        <div style="text-align: right;">
            <button class="btn btn-primary" style="  margin-right: 5px;">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                <a style="  color: white;"  href="/lists"  >
                    <?php echo $this->translate('Retour'); ?>
                </a>   
            </button>
            <?php
            echo $this->formInput($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?>


        </div>
    </div>
</div>