<div class="page-header">
    <div class="page-content-area">
        <div class="page-header">
            <h1>
                <?php echo $this->translate('Modifier Municipalité'); ?> 

            </h1>
        </div><!-- /.page-header -->


        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url('delegation', array('action' => 'edit', 'id' => $this->id)));
        $form->prepare();

        echo $this->form()->openTag($form) . PHP_EOL;
        ?>
        <?php echo $this->formInput($form->get('id')); ?>
         <?php echo $this->formInput($form->get('deate_creation')); ?>
        <div class=" col-xs-12 col-lg-12">

            <?php if ($this->messageErreur == "true") {
                ?>
                <div class="alert alert-block alert-danger">
                    <p style="color: red;font-weight: bold;">
                        <?php echo $this->translate($this->message) ?>
                    </p>
                </div>
            <?php } ?>



            <?php if ($this->success == "true") {
                ?>

                <div class="alert alert-block alert-success">
                    <p style="font-weight: bold;">
                        <?php echo $this->translate($this->messageSuccess) ?>
                    </p>
                </div>
            <?php } ?>

        </div>
        <div class=" col-xs-12 col-lg-6">
            <div class="profile-user-info profile-user-info-striped">
                
                
                   <div class="profile-info-row">
                    <div class="profile-info-name"> <?php echo $this->formLabel($form->get('idGouvernorat')); ?>  </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="about"> <?php
                            echo $this->formElement($form->get('idGouvernorat'));
                            echo $this->formElementErrors($form->get('idGouvernorat'));
                            ?></span>
                    </div>
                </div>
                
                <div class="profile-info-row">
                    <div class="profile-info-name">
                        <?php echo $this->formLabel($form->get('nom')); ?> 
                    </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="username">
                            <?php
                            echo $this->formInput($form->get('nom'));
                            echo $this->formElementErrors($form->get('nom'));
                            ?>
                        </span>
                    </div>
                </div>
                
              
               
             



            </div>

        </div>
        
        
          <div class=" col-xs-12 col-lg-6">
            <div class="profile-user-info profile-user-info-striped">
                
                
               
                
                <div class="profile-info-row">
                    <div class="profile-info-name"> 
                        <?php echo $this->formLabel($form->get('nomArabe')); ?> 
                    </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="username">
                            <?php
                            echo $this->formInput($form->get('nomArabe'));
                            echo $this->formElementErrors($form->get('nomArabe'));
                            ?>
                        </span>
                    </div>
                </div>
                
                
                 <div class="profile-info-row">
                    <div class="profile-info-name"> 
                        <?php echo $this->formLabel($form->get('nbrChaise')); ?> 
                    </div>

                    <div class="profile-info-value">
                        <span class="editable editable-click" id="username">
                            <?php
                            echo $this->formInput($form->get('nbrChaise'));
                            echo $this->formElementErrors($form->get('nbrChaise'));
                            ?>
                        </span>
                    </div>
                </div>
               
             



            </div>

        </div>

       
        <div class="space-20"></div>
        <div style="text-align: right;">
            <button class="btn btn-primary" style="  margin-right: 5px;">
                <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
                <a style="  color: white;"  href="/delegation"  >
                    <?php echo $this->translate('Retour'); ?>
                </a>   
            </button>
            <?php
            echo $this->formInput($form->get('submit'));
            echo $this->formElementErrors($form->get('submit'));
            ?>


        </div>
    </div>
</div>