<?php
echo $this->doctype();
?>
<html lang="fr">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta charset="utf-8" />
        <title> <?php echo $this->translate('MOURAKIBOUN') ?></title>

        <meta name="description" content="User login page" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

         <link href="/img/logo-icon.png" rel="shortcut icon" />
        <link rel="stylesheet" href="/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/css/font-awesome.min.css" />

        <!-- text fonts -->
        <link rel="stylesheet" href="/css/css.css" />

        <!-- ace styles -->
        <link rel="stylesheet" href="/css/ace.min.css" />

        <link rel="stylesheet" href="/css/ace-rtl.min.css" />

       
    </head>

    <body class="login-layout">
        <div class="main-container">
            <div class="main-content">
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        <div class="login-container">
                            <div class="center">
                                 <img  alt="MOURAKIBOUN" src="/img/Logo-mourakiboun.png ">
                                
                            </div>

                            <div class="space-6"></div>

                            <div class="position-relative">
                                <div id="login-box" class="login-box visible widget-box no-border">
                                    <div class="widget-body">
                                        <div class="widget-main">
                                            <h4 class="header blue lighter bigger">
                                                <i class="ace-icon ">
                                                    <img  alt="MOURAKIBOUN" src="/img/logo-icon.png" style="width: 11%;">
                                                </i>
                                                <?php echo $this->translate("Accéder à votre compte"); ?>
                                            </h4>
                                            <?php if ($this->messageErreur == "true") {
                                                ?>
                                                <div class="alert alert-block alert-danger">
                                                    <p style="color: red;font-weight: bold;">
                                                        <?php echo $this->translate($this->message) ?>
                                                    </p>
                                                </div>
                                            <?php } ?>
                                            <div class="space-6">

                                            </div>

                                            <?php
                                            $form = $this->form;
                                            $form->prepare();
                                            echo $this->form()->openTag($form);
                                            ?>
                                            <fieldset>
                                                <label class="block clearfix">
                                                    <span class="block input-icon input-icon-right">
                                                        <?php echo $this->formRow($form->get('usr_login')); ?>
                                                        <i class="ace-icon fa fa-user"></i>
                                                    </span>
                                                </label>

                                                <label class="block clearfix">
                                                    <span class="block input-icon input-icon-right">
                                                        <?php echo $this->formRow($form->get('usr_password')); ?>
                                                        <i class="ace-icon fa fa-lock"></i>
                                                    </span>
                                                </label>
                                                <?php echo $this->formRow($form->get('csrf')); ?>
                                                <div class="space"></div>

                                                <div class="clearfix" style="float:right">


                                                    <?php echo $this->formSubmit($form->get('submit')); ?>
                                                </div>

                                                <div class="space-4"></div>
                                            </fieldset>
                                            <?php echo $this->form()->closeTag(); ?>



                                        </div><!-- /.widget-main -->

                                        <div class="toolbar clearfix">
                                            <div>
                                                <a href="/pwdoublie"  class="forgot-password-link">
                                                    <i class="ace-icon fa fa-arrow-left"></i>
                                                    <?php echo $this->translate("Mot de passe oublié"); ?>
                                                </a>
                                            </div>


                                        </div>
                                    </div><!-- /.widget-body -->
                                </div><!-- /.login-box -->

                            </div><!-- /.position-relative -->

                        </div>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.main-content -->
        </div><!-- /.main-container -->

        <!-- basic scripts -->

        
        <script type="text/javascript">
            window.jQuery || document.write("<script src='/js/jquery.min.js'>" + "<" + "/script>");
        </script>

        <!-- <![endif]-->

        <!--[if IE]>
<script type="text/javascript">
window.jQuery || document.write("<script src='/js/jquery1x.min.js'>"+"<"+"/script>");
</script>
<![endif]-->
        <script type="text/javascript">
            if ('ontouchstart' in document.documentElement)
                document.write("<script src='/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
        </script>

        <!-- inline scripts related to this page -->
        <script type="text/javascript">
            jQuery(function($) {
                $(document).on('click', '.toolbar a[data-target]', function(e) {
                    e.preventDefault();
                    var target = $(this).data('target');
                    $('.widget-box.visible').removeClass('visible');//hide others
                    $(target).addClass('visible');//show target
                });
            });



            //you don't need this, just used for changing background
            jQuery(function($) {
                $('#btn-login-dark').on('click', function(e) {
                    $('body').attr('class', 'login-layout');
                    $('#id-text2').attr('class', 'white');
                    $('#id-company-text').attr('class', 'blue');

                    e.preventDefault();
                });
                $('#btn-login-light').on('click', function(e) {
                    $('body').attr('class', 'login-layout light-login');
                    $('#id-text2').attr('class', 'grey');
                    $('#id-company-text').attr('class', 'blue');

                    e.preventDefault();
                });
                $('#btn-login-blur').on('click', function(e) {
                    $('body').attr('class', 'login-layout blur-login');
                    $('#id-text2').attr('class', 'white');
                    $('#id-company-text').attr('class', 'light-blue');

                    e.preventDefault();
                });

            });
        </script>
    </body>
</html>
