<?php
echo $this->doctype();

?>
<html lang="fr">
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta charset="utf-8" />
        <title> <?php echo $this->translate('MOURAKIBOUN - Mot de passe oublié') ?></title>

        <meta name="description" content="User login page" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

        <!-- bootstrap & fontawesome -->
        <link rel="stylesheet" href="/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/css/font-awesome.min.css" />

        <!-- text fonts -->
        <link rel="stylesheet" href="/css/css.css" />

        <!-- ace styles -->
        <link rel="stylesheet" href="/css/ace.min.css" />

        <!--[if lte IE 9]>
                <link rel="stylesheet" href="/css/ace-part2.min.css" />
        <![endif]-->
        <link rel="stylesheet" href="/css/ace-rtl.min.css" />

        <!--[if lte IE 9]>
          <link rel="stylesheet" href="/css/ace-ie.min.css" />
        <![endif]-->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

        <!--[if lt IE 9]>
        <script src="/js/html5shiv.js"></script>
        <script src="/js/respond.min.js"></script>
        <![endif]-->
    </head>

    <body class="login-layout">
        <div class="main-container">
            <div class="main-content">
                <div class="row">
                    <div class="col-sm-10 col-sm-offset-1">
                        <div class="login-container">
                            <div class="center">

                                <h4 class="blue" id="id-company-text"><?php echo $this->translate("Bienvenue à MOURAKIBOUN"); ?></h4>
                            </div>

                            <div class="space-6"></div>

                            <div class="position-relative">
                                
                                
                                <div id="forgot-box" class="forgot-box visible widget-box no-border">
                                    <div class="widget-body">
                                        <div class="widget-main">
                                            <h4 class="header red lighter bigger">
                                              
                                                <?php echo $this->translate("Récupérer mot de passe"); ?>
                                            </h4>
                                            
                                            <?php if ($this->messageErreur == "true") {
                                                ?>
                                            
                                            
                                             <div class="alert alert-block alert-danger">
                            <p style="color: red;font-weight: bold;">
                                <?php echo $this->translate($this->message); ?></p></div>
                                                
                                            <?php } ?>
                                            
                                            <?php if ($this->success == "true") {
                                                ?>
                                            
                                                <div class="alert alert-block alert-success">
                                                    <p style="font-weight: bold;">
                                                        <?php echo $this->translate($this->messageSuccess) ?>
                                                    </p>
                                                </div>
                                            <?php } ?>

                                            <div class="space-6"></div>
                                            

                                           
                                                <?php 
                                                $form = $this->form;
                                                $form->prepare();
                                                echo $this->form()->openTag($form);
                                                
                                                ?>
                                                <fieldset>
                                              
                                                   
                                                    <label class="block clearfix">
                                                        <span class="block input-icon input-icon-right">
                                                            <?php $this->translate('Email'); ?>
                                                            <i class="ace-icon fa fa-user"></i>
                                                        </span>
                                                    </label>
                                                    
                                            
                                                    
                                                
                                                    <label class="block clearfix">
                                                        <span class="block input-icon input-icon-right">
                                                            <?php echo $this->formRow($form->get('mailUser')); ?>
                                                            <i class="ace-icon fa fa-envelope"></i>
                                                        </span>
                                                    </label>
                                                    
                                                   <?php echo $this->formRow($form->get('csrf')); ?>

                                                    <div class="clearfix">
                                                        <div class="clearfix">
                                                        <div style="text-align: right;">
                                                        <?php echo $this->formSubmit($form->get('submit')); ?>
                                                       </div>
                                                           
                                                    </div>
                                                    </div>
                                                </fieldset>
                                          
                                        </div><!-- /.widget-main -->

                                        <div class="toolbar center">
                                            <a href="/admin" class="back-to-login-link">
                                                   <?php echo $this->translate("Retour à l'interface d'authentification"); ?>  
                                               
                                                
                                                <i class="ace-icon fa fa-arrow-right"></i>
                                            </a>
                                        </div>
                                    </div><!-- /.widget-body -->
                                </div><!-- /.forgot-box -->
                                
                       
                            </div><!-- /.position-relative -->

                     
                        </div>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.main-content -->
        </div><!-- /.main-container -->

        <!-- basic scripts -->

        <script type="text/javascript">
            window.jQuery || document.write("<script src='/js/jquery.min.js'>" + "<" + "/script>");
        </script>

        <!-- <![endif]-->

        <!--[if IE]>
<script type="text/javascript">
window.jQuery || document.write("<script src='/js/jquery1x.min.js'>"+"<"+"/script>");
</script>
<![endif]-->
        <script type="text/javascript">
            if ('ontouchstart' in document.documentElement)
                document.write("<script src='/js/jquery.mobile.custom.min.js'>" + "<" + "/script>");
        </script>

        <!-- inline scripts related to this page -->
        <script type="text/javascript">
            jQuery(function($) {
                $(document).on('click', '.toolbar a[data-target]', function(e) {
                    e.preventDefault();
                    var target = $(this).data('target');
                    $('.widget-box.visible').removeClass('visible');//hide others
                    $(target).addClass('visible');//show target
                });
            });



            //you don't need this, just used for changing background
            jQuery(function($) {
                $('#btn-login-dark').on('click', function(e) {
                    $('body').attr('class', 'login-layout');
                    $('#id-text2').attr('class', 'white');
                    $('#id-company-text').attr('class', 'blue');

                    e.preventDefault();
                });
                $('#btn-login-light').on('click', function(e) {
                    $('body').attr('class', 'login-layout light-login');
                    $('#id-text2').attr('class', 'grey');
                    $('#id-company-text').attr('class', 'blue');

                    e.preventDefault();
                });
                $('#btn-login-blur').on('click', function(e) {
                    $('body').attr('class', 'login-layout blur-login');
                    $('#id-text2').attr('class', 'white');
                    $('#id-company-text').attr('class', 'light-blue');

                    e.preventDefault();
                });

            });
        </script>
    </body>
</html>
